language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get -q -y upgrade
  - mkdir build
  - cd build
  - cmake --target all -- ..

script:
  - make clean
  - make all
