language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7S
    packages:
      - cmake
      - gcc-5
      - g++-5
      - clang-3.7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq cmake -y
  - mkdir build
  - cd build
  - cmake --target all -- ..

script:
  - make clean
  - make all
