language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - mkdir build
  - cd build
  - cmake --target all -- ..

script:
  - cmake --build .\build --target all -- .
