language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade --fix-missing cmake
  - mkdir build
  - cd build
  - cmake --target all -- ..

script:
  - make clean
  - make all
